apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-service
spec:
  type: NodePort
  selector:
    app: devops-pipeline-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
