stages:
  - stage_build
  - stage_test
  - stage_deploy

variables:
  OWNER_NAME: Alex
  CICD_VERSION: v1.0
  LOG_FILE_NAME: log.txt

build.job:
  stage: stage_build
  script:
    - echo "---Start Build---"
    - echo "Building..." >> $LOG_FILE_NAME
    - echo "---Build Completed---"

test_job1:
  stage: stage_test
  script:
    - echo "---Start Test1---"
    - echo "Testing..." >> $LOG_FILE_NAME
    - echo "---Test1 Completed---""

test_job2:
  stage: stage_test
  script:
    - echo "---Start Test2---"
    - echo "Testing..." >> $LOG_FILE_NAME
    - echo "---Test2 Completed---""

deploy_to_dev_job:
  stage: stage_deploy
  script:
    - echo "---Start Deploy---"
    - echo "Deploying..." >> $LOG_FILE_NAME
    - echo "---Deploy Completed---""
    - cat $LOG_FILE_NAME
